### ISSUE TITLE
Neerslag card not showing

### ISSUE THREAD

**Issue by pvdburgt-new** [aex351/home-assistant-neerslag-app#8] opened 2021-05-24 14:32 UTC
I have installed the component using HACS. Installed it in integrations. So far so good.
I don't see the "neerslag" card though.

**Comment by pvdburgt-new** [comment] 2021-05-29 07:30
It does show now. Caching seemed to be the problem. On the app it still does not work.

**Comment by aex351** [comment] 2021-05-31 23:35
The app might be holding on to the cache. Try restarting the app (force close) and clear the cache. That should refresh the dashboard.

The problem is as far as I can tell not caused by the Neerslag Card.

**Comment by aex351** [comment] 2021-06-26 23:48
Closing this issue as the root cause is with Home Assistant itself. Continuing under #11 to see if there is a way for the Neerslag App to force refresh the cache.

**Closed by aex351** 2021-06-26 23:48 UTC
Labels: invalid
