### ISSUE TITLE
Buienalarm seems to be off by a factor of 10

### ISSUE THREAD

**Issue by Woutch** [aex351/home-assistant-neerslag-app#45] opened 2023-06-22 14:13 UTC
When I check the buienalarm website it shows 5mm/h, but the Neeslag Card only shows 0.5.

Buienradar seems to be correct.

![image](https://github.com/aex351/home-assistant-neerslag-app/assets/3136903/9f0428e0-d8cc-4556-a96f-228ba6269940)

![image](https://github.com/aex351/home-assistant-neerslag-app/assets/3136903/4c0660c2-424f-4ad3-bf14-1efb6e16f68a)

![image](https://github.com/aex351/home-assistant-neerslag-app/assets/3136903/e8841824-8519-4436-829a-784dd37993f6)

I also use the location settings from home assistant if this makes a difference.

Many Thanks,
Wouter

**Comment by rononline** [comment] 2023-06-22 14:43
I notice the same behaviour. The values are not correct for Buienalarm. An sin the sensor I also see a different location at bounds:

```
bounds:
'N': 55.973602
E: 10.856429
S: 48.895302
W: 0
```

```
success: true
start: 1687434000
start_human: '13:40'
temp: 25
delta: 300
precip:
- 0
- 0.1
- 0.1
- 0.2
- 0.2
- 0.2
- 0.2
- 0.2
- 0.2
- 0.2
- 0.1
- 0.1
- 0.1
- 0.3
- 0.5
- 0.4
- 0.4
- 0.4
- 0.5
- 0.7
- 0.5
- 0.3
- 0.3
- 0.2
- 0.3
levels:
light: 0.25
moderate: 1
heavy: 2.5
grid:
x: 326
'y': 461
source: nl
bounds:
'N': 55.973602
E: 10.856429
S: 48.895302
W: 0
```

**Comment by erkr** [comment] 2023-07-04 22:48
Yes, for me these values also don’t match with the values of the official app, probably a location mismatch

**Comment by EvertJob** [comment] 2023-08-24 13:44
You need to find `rain.push(item)` in neerslag-card.js and change it to `rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))` save and do not restart yet!

Open sensors.py, find for `cdn-secure.buienalarm` and replace the **whole** line (263 at my place, but I've modified it much more) with this:
```https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm'```

Then reboot and the data should be fine again

**Comment by paqpaqpaq** [comment] 2023-08-25 13:04
> You need to find `rain.push(item)` in neerslag-card.js and change it to `rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))` save and do not restart yet!
> 
> Open sensors.py, find for `cdn-secure.buienalarm` and replace the **whole** line (263 at my place, but I've modified it much more) with this: `url = https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm'`
> 
> Then reboot and the data should be fine again

"&unit=mm" can be discarded as well.

**Comment by EvertJob** [comment] 2023-08-25 13:06
> > You need to find `rain.push(item)` in neerslag-card.js and change it to `rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))` save and do not restart yet!
> > Open sensors.py, find for `cdn-secure.buienalarm` and replace the **whole** line (263 at my place, but I've modified it much more) with this: `url = https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm'`
> > Then reboot and the data should be fine again
> 
> "&unit=mm" can be discarded as well.

Spot on but it was in the original code as well so no idea what the function of it was or should be.

**Comment by erkr** [comment] 2023-08-28 09:09
> You need to find `rain.push(item)` in neerslag-card.js and change it to `rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))` save and do not restart yet!
> 
> Open sensors.py, find for `cdn-secure.buienalarm` and replace the **whole** line (263 at my place, but I've modified it much more) with this: `url = https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm'`
> 
> Then reboot and the data should be fine again

Hi, 
I tried it as well but neerslag  doesn't  load anymore in my case. This is the error:
``` 
  File "/config/custom_components/neerslag/sensor.py", line 263
    url = https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm'
                                                                                                                             ^
SyntaxError: unterminated string literal (detected at line 263)
``` 
Do I have to put ""  around  the url string?

**Comment by paqpaqpaq** [comment] 2023-08-28 14:20
> > You need to find `rain.push(item)` in neerslag-card.js and change it to `rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))` save and do not restart yet!
> > Open sensors.py, find for `cdn-secure.buienalarm` and replace the **whole** line (263 at my place, but I've modified it much more) with this: `url = https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm'`
> > Then reboot and the data should be fine again
> 
> Hi, I tried it as well but neerslag doesn't load anymore in my case. This is the error:
> 
> ```
>   File "/config/custom_components/neerslag/sensor.py", line 263
>     url = https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm'
>                                                                                                                              ^
> SyntaxError: unterminated string literal (detected at line 263)
> ```
> 
> Do I have to put "" around the url string?
> 
> And replace a particular instance of `rain.push(item)` or all of them?
> 
> Best Eric

this shoul work:


```
    async def getBuienalarmData(self) -> str:
        data = json.loads('{"data":""}')
        # return data
        try:
            timeout = aiohttp.ClientTimeout(total=5)
            async with aiohttp.ClientSession() as session:
                url = 'https://cdn-secure.buienalarm.nl/api/3.4/forecast.php?lat=' + self._lat + '&lon=' + self._lon + '&region=nl&unit=mm' + str(rand.randint(0, 999999999999999))
                async with session.get(url, timeout=timeout) as response:
                    html = await response.text()
                    dataRequest = html.replace('\r\n', ' ')
                    if dataRequest == "" :
                        dataRequest = ""
                    data = json.loads('{"data":' + dataRequest + '}')
                    # _LOGGER.info(data)
                    await session.close()
        except:
            _LOGGER.info("getBuienalarmData - timeout")
            pass

        return data
```

**Comment by aex351** [comment] 2023-08-28 17:59
The Neerslag app is showing the data as received by the Buienalarm API, which is returned as mm/h. Changing the API call will return raw data which needs to be converted to mm/h using a formula.

The issue as reported here describes the Neerslag App is showing 0,6 mm/h while the website/app shows 6 mm/h. 

If it's 0,6 mm/h vs 6,0 mm/h then the API returns different data or the Neerslag App is doing something wrong with the received data. I noticed before that the API data is not always equal to that of the website/app. 

Looking in to this.

**Comment by paqpaqpaq** [comment] 2023-08-28 18:13
It is not always factor 10, that is the problem. This shows when there is heavy rain e.g. over 20 or 30 mm/h
So, raw data + the math fixes it.

**Comment by erkr** [comment] 2023-08-28 18:22
I have it ruining now with the modifications 😊 and waiting for some rain 🫢

**Comment by EvertJob** [comment] 2023-08-28 18:34
It looks that @aex351 **don't want to use are working solution**.

We know that your original code is reporting in mm/h but the problem is that the data is not correct. When using raw data and formatting it with the right code/sum everything is working fine.

So, @aex351 why are you not using our solution?

**Comment by aex351** [comment] 2023-08-28 21:26
The statement "the data is not correct" is not a valid. It is data provided by Buienalarm and used as-is. 

The statement can be "the current data does not match the current website/app". And by using the exact same api but with raw data and converting the values manually, we can match it.

Anyway, in both cases we use the official api as provided by Buienalarm. 

Let's first test using the raw data to see if there is an actual improvement. Because right now. Often enough the current implementation also matches the website/app. If the raw data with formula actually proves to give better results. We will of course change it.

**Comment by paqpaqpaq** [comment] 2023-08-28 21:48
well, I've been using it for some days now with the raw data, and is spot on :)
<img width="354" alt="Scherm­afbeelding 2023-08-25 om 08 59 19" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/1edd5ae2-b062-4277-aa50-c5156ad0c829">

**Comment by erkr** [comment] 2023-08-29 09:57
@aex351 for me the Buienalarm values are way off most off the time compared to their mobile app and buienradar. The deviations are definitely not a fixed number (like 10). My initial thought was therefore a location mismatch. But the solution using the raw values sounds very promising to me.
I modified the code as described and will report back the results later. Today is dry, but it will rain in my area tomorrow.

**Comment by erkr** [comment] 2023-08-30 08:52
No this is really not right:
![image](https://github.com/aex351/home-assistant-neerslag-app/assets/4363599/31815251-2ee0-4e09-9a78-41e22509e894)
It is 100 time to much now. Maybe I thuis not change replace the right rain.push calls

**Comment by erkr** [comment] 2023-08-30 09:41
I changed getBuienradarData in sensor.py with your version.
I replaced rain.push in both formatBuienalarmData and formatBuienalarmDataAndere methods

**Comment by aex351** [comment] 2023-08-30 10:24
The following I just observed: the official Buienalarm app (Android) shows different data compared to the official Buienalarm website. When I compare both of these to the Neerslag App that uses the official Buienalarm API again it shows different data.

In all cases. It shows that it will rain. Only the quantity slightly differs. Also there is a small difference when an actual GPS location is used (that gets translated in to a city name) vs just using a city name (on the website or app for example). For the above observation I used both GPS and just searching a city by name to have all options covered.

So there seems to be a discrepancy between the official website, the official Android app and the official api.

**Comment by paqpaqpaq** [comment] 2023-08-30 10:34
@erkr purge the cache, you never know
Also make sure you are at the correct sensor in the .js

**Comment by EvertJob** [comment] 2023-08-30 10:36
> The following I just observed: the official Buienalarm app (Android) shows different data compared to the official Buienalarm website. When I compare both of these to the Neerslag App that uses the official Buienalarm API again it shows different data.
> 
> In all cases. It shows that it will rain. Only the quantity slightly differs. Also there is a small difference when an actual GPS location is used (that gets translated in to a city name) vs just using a city name (on the website or app for example). For the above observation I used both GPS and just searching a city by name to have all options covered.
> 
> So there seems to be a discrepancy between the official website, the official Android app and the official api.

And what is the fix?

**Comment by aex351** [comment] 2023-08-30 11:28
There is no fix. It is all data from Buienalarm. I'm guessing they have various systems / api's. Each with its own characteristics. When I looked earlier for example the website reported 2,0 mm rain. The app reported 1,2 mm rain and the Neerslag app reported 0,8 mm for a specific time. Will see how the raw data matches any of this.

**Comment by EvertJob** [comment] 2023-08-30 11:32
As far as I can see there is no official API from Buienalarm, there is no documentation at all, so it makes sense that the data is not accurate.

There is a fix to match the amount of rain from the website to Home Assistant but you're a bit stubborn in it. Change youre code for the solution I've posted before and everything is fine.

**Comment by paqpaqpaq** [comment] 2023-08-30 11:44
All I can say this is spot on (with the website and app)

<img width="319" alt="Scherm­afbeelding 2023-08-30 om 13 43 43" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/27022d8f-ce1c-4a3f-9bfc-0b5adba868ef">
<img width="716" alt="Scherm­afbeelding 2023-08-30 om 13 43 33" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/2ff70a53-5e6a-4b2a-969a-637dfe4c8729">

**Comment by erkr** [comment] 2023-08-30 14:41
The deviation we observed is not "slightly", but up to 10 times as reported. For some reason I didn't modify the two files correctly, as in now see 100 times off. @paqpaqpaq maybe you can post the whole files you modified?!

**Comment by paqpaqpaq** [comment] 2023-08-30 16:24
@ erkr I think your error is in the neerslag-card.js

I suggest you take a 'fresh' one from the code on this git,
https://github.com/aex351/home-assistant-neerslag-app/blob/main/custom_components/neerslag/home-assistant-neerslag-card/neerslag-card.js
From that file change line 823
`			rain.push(item)
`

to
`			rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))
`

**Comment by aex351** [comment] 2023-08-30 16:43
In your last screenshot you can clearly see that the values between the api and website don't match up. Website reports 2,0 mm/h and the api reports 2,37 mm/h on the spike. This is using the raw data with formula. Now try using the api with calculated values. And see how that compares.

**Comment by EvertJob** [comment] 2023-08-30 16:50
> In your last screenshot you can clearly see that the values between the api and website don't match up. Website reports 2,0 mm/h and the api reports 2,37 mm/h on the spike. This is using the raw data with formula. Now try using the api with calculated values. And see how that compares.

Is it so hard to admit that my/our fix is working well? 

Or fix it or close this issue.

**Comment by aex351** [comment] 2023-08-30 17:18
Currently there is nothing to be fixed. It has not been proven that using the raw data from the api actually improves anything. 

Now based on your statement the Buienalarm website doesn't use decimals. I also observe this. Everything above 1 mm/h gets rounded. In the app it uses decimals.

Now as a test, I compare Buienalarm website with the Buienalarm app. And I see 5,6 mm/h and 13 mm/h for the exact same location. So which one is correct and which one is wrong.

**Comment by paqpaqpaq** [comment] 2023-08-30 17:20
> In your last screenshot you can clearly see that the values between the api and website don't match up. Website reports 2,0 mm/h and the api reports 2,37 mm/h on the spike. This is using the raw data with formula. Now try using the api with calculated values. And see how that compares.

I did, and get the same crazy results as anyone else. 
The website rounds everything above 1 mm. 
It simply fits. 
<img width="1053" alt="Scherm­afbeelding 2023-08-24 om 16 00 03" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/6f40c83e-dee1-422b-b7fe-4487097558f4">

<img width="347" alt="Scherm­afbeelding 2023-08-30 om 19 19 48" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/d8a55925-81a9-450c-8448-547d452b7f1d">

**Comment by paqpaqpaq** [comment] 2023-08-30 17:22
> Currently there is nothing to be fixed. It has not been proven that using the raw data from the api actually improves anything.
>

Then there's nothing left I can do to help.


> Currently there is nothing to be fixed. It has not been proven that using the raw data from the api actually improves anything.
> 
> Now based on your statement the Buienalarm website doesn't use decimals. I also observe this. Everything above 1 mm/h gets rounded. In the app it uses decimals.
> 
> Now as a test, I compare Buienalarm website with the Buienalarm app. And I see 5,6 mm/h and 13 mm/h for the exact same location. So which one is correct and which one is wrong.

They are both 'right', just two different datacenters with different models. ALL weather models deviate.

**Comment by erkr** [comment] 2023-09-01 11:24
Hi @EvertJob 
Thanks for looking into that file:
[sensor.zip](https://github.com/aex351/home-assistant-neerslag-app/files/12497343/sensor.zip)

Best Eric

**Comment by EvertJob** [comment] 2023-09-01 11:39
Can you share the sensor data also? 

This can be found under developer tools

**Comment by EvertJob** [comment] 2023-09-01 11:42
You can find a exactly copy of my working version here: https://drive.google.com/drive/folders/1gca-ZQs0ew4Wg58FZ99Roi-u-k7ni-0V?usp=sharing

**Comment by erkr** [comment] 2023-09-01 14:06
> You can find a exactly copy of my working version here: https://drive.google.com/drive/folders/1gca-ZQs0ew4Wg58FZ99Roi-u-k7ni-0V?usp=sharing

Thanks! Will try it and report back. Will share the sensor data once it rains again

**Comment by EvertJob** [comment] 2023-09-01 16:00
> > You can find a exactly copy of my working version here: https://drive.google.com/drive/folders/1gca-ZQs0ew4Wg58FZ99Roi-u-k7ni-0V?usp=sharing
> 
> Thanks! Will try it and report back. Will share the sensor data once it rains again

It’s possible to create fake data. Just change some 0 values to something useful (100 for example) under developer tools

**Comment by erkr** [comment] 2023-09-01 16:24
@EvertJob 
I replaced the neerslag folder fully with your version, but now both the x-y axis infos and the buienalarm data is not displayed anymore:
![image](https://github.com/aex351/home-assistant-neerslag-app/assets/4363599/8d2d1000-669d-4172-ad69-d0bee165fe33)
The buien alarm sensor is present and updated: 
``` 
state: 0.512274137550046

data:
  success: true
  start: 1693584600
  start_human: '18:10'
  temp: 21
  delta: 300
  precip:
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  levels:
    light: 0.25
    moderate: 1
    heavy: 2.5
  grid:
    x: 402
    'y': 502
  source: nl
  bounds:
    'N': 55.973602
    E: 10.856429
    S: 48.895302
    W: 0
icon: mdi:weather-cloudy
friendly_name: neerslag_buienalarm_regen_data
```

**Comment by EvertJob** [comment] 2023-09-01 16:38
> @EvertJob I replaced the neerslag folder fully with your version, but now both the x-y axis infos and the buienalarm data is not displayed anymore: ![image](https://user-images.githubusercontent.com/4363599/265074366-8d2d1000-669d-4172-ad69-d0bee165fe33.png) The buien alarm sensor is present and updated:
> 
> ```
> state: 0.512274137550046
> 
> data:
>   success: true
>   start: 1693584600
>   start_human: '18:10'
>   temp: 21
>   delta: 300
>   precip:
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>   levels:
>     light: 0.25
>     moderate: 1
>     heavy: 2.5
>   grid:
>     x: 402
>     'y': 502
>   source: nl
>   bounds:
>     'N': 55.973602
>     E: 10.856429
>     S: 48.895302
>     W: 0
> icon: mdi:weather-cloudy
> friendly_name: neerslag_buienalarm_regen_data
> ```

That’s correct, @paqpaqpaq and I modified the entire card. If this works that you can compare the JS files

**Comment by paqpaqpaq** [comment] 2023-09-01 16:48
> @EvertJob I replaced the neerslag folder fully with your version, but now both the x-y axis infos and the buienalarm data is not displayed anymore: ![image](https://user-images.githubusercontent.com/4363599/265074366-8d2d1000-669d-4172-ad69-d0bee165fe33.png) The buien alarm sensor is present and updated:
> 
> ```
> state: 0.512274137550046
> 
> data:
>   success: true
>   start: 1693584600
>   start_human: '18:10'
>   temp: 21
>   delta: 300
>   precip:
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>     - 0
>   levels:
>     light: 0.25
>     moderate: 1
>     heavy: 2.5
>   grid:
>     x: 402
>     'y': 502
>   source: nl
>   bounds:
>     'N': 55.973602
>     E: 10.856429
>     S: 48.895302
>     W: 0
> icon: mdi:weather-cloudy
> friendly_name: neerslag_buienalarm_regen_data
> ```

The 'app' part of this integration will create the sensor for you so not sure whether this will work as you did now. 
There should not be a sensor in configuration.yaml
You need to create it through the integration.


Nevertheless, all of this hassle really shouldn't be a concern in my opinion.

**Comment by paqpaqpaq** [comment] 2023-09-01 17:10
it is just two things:
- the sensor.py, remove the units and all after it of the API call URL
- add (change) the equation for calculating the raw data in neerslag-card.js

**Comment by aex351** [comment] 2023-09-01 20:28
On various occasions now I checked the data from the Buienalarm api. The api can return the data in the following format:

- (api with mm/h) data is already in the mm/h format
- (api without mm/h) data is raw and needs to be manually calculated to the mm/h format.

So this initial issue starts by describing that the current implementation, api with mm/h, does not always match the Buienalarm website or Buienalarm api.

I have observed that the Buienalarm website and Buienalarm api does not always match.

So to further deep-dive in to the statement that the data without mm/h is accurate and the data with mm/h is not. I started to compared just the api. It turns out that both the data with mm/h and the data without mm/h (and manually calculate the values) are the same. 

The data with mm/h rounds the values to 1 decimal. So 1,54 mm/h becomes 1,5 mm/h. This means that using the data without mm/h and based on how many decimals you want it to display based of the manual calculation can be slighty more precise.

However, the Buienalarm website rounds all data above 1 mm/h to 0 decimals. So either way. The current implementation as-is is more accurate. Compared to the website.

The current conclusion is that there is no issue with the Buienalarm api and that the data as returned by the api is the same.

**Comment by erkr** [comment] 2023-09-01 20:46
@aex351 I disagree with the invalid label. Although I couldn't verify the changes proposed by others, the current version on neerslag app is definitely not correct. The rain forecast for Buienalarm in the neerslag app is most of the time way off compared to the forecast in the mobile app or website. The deviations are not just a matter of rounding

**Comment by aex351** [comment] 2023-09-01 21:23
As I explained. Buienalarm website, Buienalarm app and Buienalarm api all three can show different data for the same location and time. It is what it is. The back-end of Buienalarm itself probably processes each request slightly different. This is an internal matter of Buienalarm. Please contact them directly to address that issue.

The Neerslag App is simply a consumer of the data that is available. Now what has been proven is that using the api with mm/h and without mm/h returns the exact same results. If you want to entertain yourself by changing the current implementation using the exact same api, that is up to you. Lets just make sure to keep it factual. If someone can prove that the data for the same location and time, using the api with mm/h and without mm/h is different. We can take action to make a change.

**Comment by paqpaqpaq** [comment] 2023-09-01 21:36
Oh but that's easy :)

Here goes. this very moment "Uden":
<img width="1061" alt="Scherm­afbeelding 2023-09-01 om 23 34 20" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/5bd0b6ae-d9a9-492c-b37c-3e09a12df712">

Now the EXACT same coordinates, with units mm/h:
<img width="617" alt="Scherm­afbeelding 2023-09-01 om 23 35 23" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/2213a7d3-daa7-43b0-8614-0f661417818a">
Please show me precipitation higher than 1mm:
<img width="1261" alt="Scherm­afbeelding 2023-09-01 om 23 36 03" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/08e73633-fc97-4da7-9b8c-9c3b143bbf7e">

The raw data (might anyone feel to put that in the equation-version)
<img width="1204" alt="Scherm­afbeelding 2023-09-01 om 23 36 47" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/f2480e79-ce5b-426a-834b-0ace32424ade">

**Comment by Dennisjvdb** [comment] 2023-09-02 10:23
From the buienradar website:

"Op basis van de door u gewenste coördinaten (latitude en longitude) kunt u de neerslag tot twee uur vooruit ophalen in tekstvorm. De data wordt iedere 5 minuten geüpdatet. [Op deze pagina kunt u de neerslag in tekst vinden.](https://gps.buienradar.nl/getrr.php?lat=51&lon=3) De waarde 0 geeft geen neerslag aan (droog), de waarde 255 geeft zware neerslag aan. Gebruik de volgende formule voor het omrekenen naar de neerslagintensiteit in de eenheid millimeter per uur (mm/u):

Neerslagintensiteit = 10^((waarde-109)/32)

Ter controle: een waarde van 77 is gelijk aan een neerslagintensiteit van 0,1 mm/u."

in english:

"Based on the coordinates you provided (latitude and longitude), you can retrieve precipitation data in text format for up to two hours in advance. The data is updated every 5 minutes. On this page, you can find precipitation in text form. A value of 0 indicates no precipitation (dry), and a value of 255 indicates heavy precipitation. Use the following formula to convert it to precipitation intensity in millimeters per hour (mm/h):

Precipitation Intensity = 10^((value - 109)/32)

For reference: a value of 77 is equivalent to a precipitation intensity of 0.1 mm/h."

**Comment by EvertJob** [comment] 2023-09-02 10:55
> From the buienradar website:
> 
> "Op basis van de door u gewenste coördinaten (latitude en longitude) kunt u de neerslag tot twee uur vooruit ophalen in tekstvorm. De data wordt iedere 5 minuten geüpdatet. [Op deze pagina kunt u de neerslag in tekst vinden.](https://gps.buienradar.nl/getrr.php?lat=51&lon=3) De waarde 0 geeft geen neerslag aan (droog), de waarde 255 geeft zware neerslag aan. Gebruik de volgende formule voor het omrekenen naar de neerslagintensiteit in de eenheid millimeter per uur (mm/u):
> 
> Neerslagintensiteit = 10^((waarde-109)/32)
> 
> Ter controle: een waarde van 77 is gelijk aan een neerslagintensiteit van 0,1 mm/u."
> 
> in english:
> 
> "Based on the coordinates you provided (latitude and longitude), you can retrieve precipitation data in text format for up to two hours in advance. The data is updated every 5 minutes. On this page, you can find precipitation in text form. A value of 0 indicates no precipitation (dry), and a value of 255 indicates heavy precipitation. Use the following formula to convert it to precipitation intensity in millimeters per hour (mm/h):
> 
> Precipitation Intensity = 10^((value - 109)/32)
> 
> For reference: a value of 77 is equivalent to a precipitation intensity of 0.1 mm/h."

This is buienradar. We are discussing buienalarm but the results should be (around!) the same

**Comment by paqpaqpaq** [comment] 2023-09-02 11:11
@Dennisjvdb and 137 = 7.5

**Comment by Dennisjvdb** [comment] 2023-09-02 11:44
@paqpaqpaq 

But aren't you using the exact same formula?

`rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))`

**Comment by erkr** [comment] 2023-09-02 12:30
> Oh but that's easy :)
> 
> 
> 
> Here goes. this very moment "Uden":
> 
> <img width="1061" alt="Scherm­afbeelding 2023-09-01 om 23 34 20" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/5bd0b6ae-d9a9-492c-b37c-3e09a12df712">
> 
> 
> 
> Now the EXACT same coordinates, with units mm/h:
> 
> <img width="617" alt="Scherm­afbeelding 2023-09-01 om 23 35 23" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/2213a7d3-daa7-43b0-8614-0f661417818a">
> 
> Please show me precipitation higher than 1mm:
> 
> <img width="1261" alt="Scherm­afbeelding 2023-09-01 om 23 36 03" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/08e73633-fc97-4da7-9b8c-9c3b143bbf7e">
> 
> 
> 
> The raw data (might anyone feel to put that in the equation-version)
> 
> <img width="1204" alt="Scherm­afbeelding 2023-09-01 om 23 36 47" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/f2480e79-ce5b-426a-834b-0ace32424ade">
> 

@paqpaqpaq @EvertJob 
This illustrates the whole issue: 
The graph shows moments of heavy rain. BUT both the queries are that same (as @aex351 indicates) although in a different format, both return light rain values only!!!

My two cents: this is the rain over 5 minutes, not 1 hour.

**Comment by paqpaqpaq** [comment] 2023-09-02 12:34
> @paqpaqpaq
> 
> But aren't you using the exact same formula?
> 
> `rain.push(parseFloat(Math.pow(10, (item - 109) / 32)).toFixed(2))`


Here is bogus data manually set:
<img width="407" alt="Scherm­afbeelding 2023-09-02 om 14 33 57" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/901d0a76-9ee5-48ea-88f6-12d002b45359">
<img width="336" alt="Scherm­afbeelding 2023-09-02 om 14 33 41" src="https://github.com/aex351/home-assistant-neerslag-app/assets/34166264/8cb4c704-25cc-4ebd-8afc-ceb067742202">

**Comment by erkr** [comment] 2023-09-02 18:53
I think it is quite simple. A value of 0.9mm per 5 minutes translates to 10.8 mm per hour (x12). That is close to the 9.3mm per hour reported on the website.

**Comment by paqpaqpaq** [comment] 2023-09-02 19:44
Could be :)
In that case still not the graph we would be expecting.

**Comment by erkr** [comment] 2023-09-02 20:24
> Could be :)
> 
> In that case still not the graph we would be expecting. 

What do you mean?

**Comment by paqpaqpaq** [comment] 2023-09-03 08:05
> > Could be :)
> > In that case still not the graph we would be expecting.
> 
> What do you mean?

0.9 x 12 is _close_ to 9.3
0.1 x 12 is no where near the actual 0.1

But regardless of all what if's. I still can't see why one shouldn't work with raw data and convert that to the output you are looking for.

**Comment by erkr** [comment] 2023-09-03 11:54
> 
> 0.9 x 12 is _close_ to 9.3
> 
> 0.1 x 12 is no where near the actual 0.1
> 
> 
> 
> But regardless of all what if's. I still can't see why one shouldn't work with raw data and convert that to the output you are looking for.  It works for myself, it works for others and also for others with a different git. 

@paqpaqpaq 
You are confusing me! You provided this image that clearly indicates there where moments of heavy rain: 

![image](https://github.com/aex351/home-assistant-neerslag-app/assets/4363599/a98178f8-ce90-4bb5-95a7-6ab017f91889)

So the data with 0.9mm as max value is definitely not a value per hour. Add the values are per 5 minutes (delta 300 seconds)I presume the value is per 5 minutes, not per hour. That works result in heavy rain if ca 10mm per hour:
'Value*3600/delta'

So it doesn't matter which url is used (both contain the same data in just another format). 

I think, based on the original neerslag implementation, only the values only need to be corrected with the formula above.

**Comment by paqpaqpaq** [comment] 2023-09-03 11:58
I think my point was that when 77 = 0.1mm, the mm/h output was actually correct at that time, without any 'aftermath'

**Comment by erkr** [comment] 2023-09-03 12:02
Not an answer to my previous message 🥹

**Comment by paqpaqpaq** [comment] 2023-09-03 12:05
OK, I will give it another try.
statement A:
mm/h is correct
0.1mm was correct at some points, but 0.9 was certainly not

statement B:
mm/h is correct if calculated per hout
approx 10mm could be correct, but than the 0.1 wouldn't be

It is just unclear what we are actually looking at with the mm/h output.
I asked buienalarm this via e-mail two weeks ago. There was no reply.

**Comment by erkr** [comment] 2023-09-03 12:37
Not clear where your refer to with statements A and B.
I will give it another try yet as well:

I am just analyzing the date you provided earlier:
- The image indicates moments of heavy rain 
- the first sensor had a max value of 0.9mm (drizzle)

My point is that these sensor values just need to be multiplied by 12 (=3600/delta) to get the right values,as they appear to be perticipation per delta, but per hour

**Comment by paqpaqpaq** [comment] 2023-09-03 12:40
> Not clear where your refer to with statements A and B. I will give it another try yet as well:
> 
> I am just analyzing the date you provided earlier:
> 
> * The image indicates moments of heavy rain
> * the first sensor had a max value of 0.9mm (drizzle)
> 
> My point is that these sensor values just need to be multiplied by 12 (=3600/delta) to get the right values,as they appear to be perticipation per delta, not per hour

right, so my reply:

take e.g. positions 4, 13 and 14, value 77 = 0.1mm after calculation
the mm/h output already states 0.1mm. Multiplying by 12 would give you a wrong value.

**Comment by erkr** [comment] 2023-09-03 13:19
I guess I now understand, that would be an unwanted 1mm to much. So the raw data with the formula seems more accurate. 

Pitty I don't get your modifications working as the  values go besirk. An I loose the weeralarm in the graph when I copy your whole folder

**Comment by erkr** [comment] 2023-09-03 14:01
@paqpaqpaq 
I have your changes to the url in sensor and the push rain in the card withing now, with simulated data it looks good indeed 👍:
I simulated two values:
77 resulting in 0.1mm/h
137 resulting in 7.5mm/h
![image](https://github.com/aex351/home-assistant-neerslag-app/assets/4363599/4ef3886d-9e13-48ec-8d5b-59bd3923c438)
Thanks for your patience! The problem was that I needed to remove the file in the neerslag/_pycache_ folder before restarting. That folder is not visible using the standard file editor. Used the file browser to fix that

**Comment by aex351** [comment] 2023-09-04 10:27
Multiply by 12 is incorrect. You would technically be calculating the total amount of rainfall for the upcoming 12 hours if the rainfall remains the same. This is because the value that we are working with is mm per hour. However, it can change every 5 minutes. So if you see 5 mm/h for the duration of 5 minutes. It gives some indication on the intensity of rain for that interval.

**Comment by erkr** [comment] 2023-09-04 16:57
The values are definitely not the rain per hour. As this issue started with, the values are typically a magnitude less than the values reported in the Buienalarm app.
My current guess is it is the rain per delta period (5 minutes). But there is also a inaccuracy for low rain values. I therefore agree with the proposal to use the raw values with the formula. That formula does generate the rain per hour and seems more accurate for low values.

**Comment by erkr** [comment] 2023-09-11 19:04
App and graph in card match better, but it looks like the two small peaks in the app are counted together. The app:
![image](https://github.com/aex351/home-assistant-neerslag-app/assets/4363599/1447ca52-f9ed-48cb-8157-9748fdf3c673)
The graph
![image](https://github.com/aex351/home-assistant-neerslag-app/assets/4363599/ef71acc3-6dcc-4842-ba3e-8a6f806fb860)

**Comment by aex351** [comment] 2023-11-01 17:46
Will push an update that for Buienalarm the data without mm/h is used. It isn't the most perfect solution, as I noticed at times there can be high spikes. That seems to be leveled in the app/website. However, the data seems to more accurate.

**Closed** 2024-05-05 01:14 UTC
Labels: possible fixed
