### ISSUE TITLE
Detected integration that uses deprecated `async_get_registry` 

### ISSUE THREAD

**Issue by AbeltjeNL** [aex351/home-assistant-neerslag-app#34] opened 2022-07-07 23:24 UTC
After upgrading my test machine from 2022.6.7 to the latest 2022.07.0 my logs show the following:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103 
First occurred: 01:01:45 (2 occurrences) 
Last logged: 01:01:45

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for neerslag using this method at custom_components/neerslag/sensor.py, line 43: dev_reg = await hass.helpers.device_registry.async_get_registry()
Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for neerslag using this method at custom_components/neerslag/sensor.py, line 44: ent_reg = await hass.helpers.entity_registry.async_get_registry()

FYI :)

**Comment by aex351** [comment] 2022-07-08 01:11
Thanks for your report. This issue is a duplicate of https://github.com/aex351/home-assistant-neerslag-app/issues/28. Which has been resolved in the latest update of the `Neerslag App`.

**Closed by aex351** 2022-07-08 01:11 UTC
