### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by Bergerie** [aex351/home-assistant-neerslag-app#65] opened 2024-09-27 12:34 UTC
Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1 

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 13:23:07 (2 occurrences)
Last logged: 13:23:07

 Detected that custom integration 'neerslag' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/neerslag-card.js", "/config/custom_components/neerslag/home-assistant-neerslag-card/neerslag-card.js", False)])`; This function will be removed in 2025.7 at custom_components/neerslag/load_frontend.py, line 20: hass.http.register_static_path(FRONTEND_SCRIPT_URL, str(path_to_file), should_cache), please create a bug report at https://github.com/aex351/home-assistant-neerslag-app/issues

**Comment by MdB-Gryphon** [comment] 2024-10-15 06:55
Same issue here

**Comment by tjorim** [comment] 2024-12-03 15:42
Duplicate of #56.

**Closed** 2024-12-20 12:21 UTC
Labels: duplicate
